server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://uavngqzzwowfto:b5464664cb0118666f7307aa25308c4f031b2652c668c9779f7a665d4ef3711a@ec2-18-214-140-149.compute-1.amazonaws.com:5432/d9nludjp3rohj
    username: uavngqzzwowfto
    password: b5464664cb0118666f7307aa25308c4f031b2652c668c9779f7a665d4ef3711a
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o bootcamp DIO - Santander / Backend
